import type { Metadata } from "next";
import { Libre_Franklin } from "next/font/google";
import "./globals.css";

const LibreFranklin = Libre_Franklin({
  weight: ["400", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-libre-franklin",
});

export const metadata: Metadata = {
  title: "Landing Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${LibreFranklin.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
